language: ruby
sudo: false
branches:
  only:
  - develop
rvm: 2.5.0
before_install:
- gem update --system
before_script:
- chmod +x ./script/cibuild
cache: bundler
script: ./script/cibuild
notifications:
  email:
    on_success: never
    on_failure: always
