# Site Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed]

# Customise feed settings (uncommenting following two fields to customise feed title and description)
title:		     "IT-lift"
description:	 "Делимся полезностями"

host: 0.0.0.0
port: 3000

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor
  - bin
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE
  - docker-compose.yml

disqus:
  comments: true
  disqus_shortname: 'sevenbits'

analytics:
  yandex:
    id: 47782252
  google:
    id:

social:
  youtube:
    link: https://www.youtube.com/channel/UCSRXBJAXUzMvR2zeG5jF6MQ
  email:
    link: mailto:aloha@7bits.it
  vk:
    link: https://vk.com/itliftomsk
  web:
    link: http://courses.itlft.ru/
